name: build-and-deploy-prod
on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: "alex-brot-storefront-dev"
  REGISTRY: "ghcr.io"
  DEPLOYMENTS_REPOSITORY: "alex-brot/deployments"

permissions:
  packages: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.7.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
            ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/${{ env.IMAGE_NAME }}:latest


  bump-deployment-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k8s Repo
        uses: actions/checkout@v4
        with:
          repository: alex-brot/deployments

      - name: Modify file
        run: |
          cat ./alex-brot/overlays/dev/kustomization.yaml
          sed -i 's|\(image: ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/${{ env.IMAGE_NAME }}:\).*|\1${{ github.run_id }}|' ./alex-brot/overlays/dev/kustomization.yaml
          cat ./alex-brot/overlays/dev/kustomization.yaml

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./alex-brot/overlays/dev/kustomization.yaml
          git commit -m "Automated image version bump to ${{ github.run_id }}"
          git config --unset-all http.https://github.com/.extraheader
          git push https://${{ secrets.K3S_REPO_PAT }}@github.com/alex-brot/deployments.git HEAD:auto-bump-prod-image-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.K3S_REPO_PAT }}
          repository: ${{ env.DEPLOYMENTS_REPOSITORY }}
          head: auto-bump-prod-image-${{ github.run_id }}
          branch: auto-bump-prod-image-${{ github.run_id }}
          base: main
          delete-branch: true
          title: "[${{github.repository}}] Automated image version bump to ${{ github.run_id }}"
          body: "This PR was automatically created by the CI pipeline in the https://github.com/${{ github.repository }} repository to bump the image version of the ${{ github.repository }} service to ${{ github.run_id }}."
